import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import { NextAuthProvider } from "./Providers";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <NextAuthProvider>
          <div>
            <Header/>
            {/* <Navbar /> */}
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
